---
- name: Build, Push and Run Docker Image for Python Application
  hosts: localhost
  vars:
    image_name: "dxs01/python-app"  # Change this to your Docker Hub username and app name
    image_tag: "v0.2"
    listen_port: 5000
    docker_socket: "unix://{{ ansible_env.HOME }}/.docker/run/docker.sock"  # Change path if using Rancher Desktop

  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.command: docker --version
      register: docker_installed
      changed_when: false

    - name: Build Docker Image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        path: "{{ playbook_dir }}"
        state: present

    - name: Push Docker Image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        push: true

    - name: Run Docker Container
      community.docker.docker_container:
        name: python_app_container
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        published_ports:
          - "{{ listen_port }}:{{ listen_port }}"
        env:
          PORT: "{{ listen_port }}"
